CREATE TABLE kajur (
id_kajur INT(3) AUTO_INCREMENT PRIMARY KEY,
nama_kajur VARCHAR(50) NOT NULL,
nidn VARCHAR(20) NOT NULL,
nama_jurusan VARCHAR(30) NOT NULL,
id_user INT(5),
FOREIGN KEY (id_user) REFERENCES user(id_user) ON DELETE CASCADE ON UPDATE CASCADE);